# Generated by Django 4.2.4 on 2023-08-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_projectmedia_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="github_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_online",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectmedia",
            name="video_embed",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
