# Generated by Django 4.2.4 on 2023-08-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_project_github_link_project_project_online_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmedia",
            name="video_embed",
            field=models.TextField(default=""),
        ),
    ]
