# Generated by Django 4.2.4 on 2023-08-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_alter_projectmedia_video_embed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmedia",
            name="video_embed",
            field=models.TextField(blank=True, null=True),
        ),
    ]
