# Generated by Django 4.2.4 on 2023-08-11 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_alter_projectmedia_video_embed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectmedia",
            old_name="video_embed",
            new_name="youtube_embed",
        ),
    ]
