# Generated by Django 4.2.4 on 2023-08-11 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_rename_video_embed_projectmedia_youtube_embed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectmedia",
            name="youtube_embed",
        ),
    ]
