# Generated by Django 4.2.4 on 2023-08-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_projectmedia_youtube_embed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectmedia",
            name="youtube_embed",
        ),
        migrations.AddField(
            model_name="project",
            name="youtube_embed",
            field=models.TextField(blank=True, null=True),
        ),
    ]
