# Generated by Django 4.2.4 on 2023-08-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='email',
            field=models.EmailField(default='email', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacto',
            name='apellido',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
    ]
